---
abstract: turn your separate XS .dll+.pm into being both a .pm and .dll
author:
- Daniel Dragan <bulkdd@cpan.org>
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: ExtUtils::MakeMaker version 7.02, CPAN::Meta::Converter version 2.142690
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-Win32-PEPM
no_index:
  directory:
  - t
  - inc
requires:
  File::Slurp: '0'
version: '0.01'
